name: Windows MinGW build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  msys2-ucrt64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >
            git make
            mingw-w64-ucrt-x86_64-gcc-libgfortran
            mingw-w64-ucrt-x86_64-gcc-fortran
            mingw-w64-ucrt-x86_64-cc
            mingw-w64-ucrt-x86_64-openblas
            mingw-w64-ucrt-x86_64-arpack
            mingw-w64-ucrt-x86_64-spooles
      - name: CI-Build (UCRT64)
        run: |
          CFLAGS+=" -fopenmp -Wno-incompatible-pointer-types -Wno-implicit-function-declaration"
          FC=gfortran
          export FFLAGS="-fallow-argument-mismatch -fopenmp -O2"
          export OMP_LIBS="-lgomp -lquadmath"
          make -f Makefile_mingw

  msys2-clang64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: CLANG64
          update: true
          install: >
            git make
            mingw-w64-clang-x86_64-clang
            mingw-w64-clang-x86_64-flang
            mingw-w64-clang-x86_64-openblas
            mingw-w64-clang-x86_64-arpack
            mingw-w64-clang-x86_64-spooles
      - name: CI-Build (CLANG64)
        run: |
          CFLAGS+=" -fopenmp -Wno-implicit-function-declaration"
          FC=flang
          export FFLAGS="-fopenmp -O2 -I${MINGW_PREFIX}/include"
          export OMP_LIBS="-lomp"
          make -f Makefile_mingw
